language: python

matrix:
  include:
    - python: 2.7
      env: PACKAGES="requests<2.5"
    - python: 3.5
      env: PACKAGES="requests<2.15 aiohttp<3"
    - python: 3.6
      env: PACKAGES="requests aiohttp"

install:
  - pip install $PACKAGES pytest-cov pytest-httpbin codecov

script:
  - pytest -v --cov

after_success:
  - codecov
