language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - REQUESTS="requests==2.4.2"
  - REQUESTS="requests"

install:
  - pip install -U $REQUESTS pytest-cov codecov
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install aiohttp; fi

script:
  - pytest -v --cov

after_success:
  - codecov
