dist: xenial
language: python

matrix:
  include:
    - python: 2.7
      env: PACKAGES="requests<2.16"
    - python: 3.5
      env: PACKAGES="requests<2.18"
    - python: 3.6
      env: PACKAGES="requests<2.20 httpx"
    - python: 3.7
      env: PACKAGES="requests<2.22 httpx"
    - python: 3.8
      env: PACKAGES="requests httpx"

install:
  - pip install $PACKAGES pytest pytest-cov pytest-httpbin codecov

script:
  - pytest -v --cov

after_success:
  - codecov

deploy:
  provider: pypi
  user: coady
  password:
    secure: s57LhvWUdwagf5aV9JosyUhcnYugvJRxBbNvUSi8r7Osmnyj155BudMNPAJeKuNeXXvO3epuUwAjZB4AbrPfv5Wg5RXbt63zfoBXHzD20tuPHrYJaA29GtDJNNey0BHqQxoj6PFuaxW2vJDd5xcpf5uhyuYnCwdBjHgpZWDY0iFkfI8CHeBLOO5MHaflt35nZTzXsCdLlvnFzPaLJ43AdS4qcaMqVt3zmwLl2ig6XJcghwh54SkEtQW+JDC8Fhth0k78N8VZlbJYjfg6QUBxa1/8kHDbAJBV6DbrwbhoEO/2RPEJuTyK+0SLGgoF+wvvMZDv/jJK7aBAWgSnWG5V5b6LDwEBEyVo8YWasjYvxRIimif2qf1sUMQJE//hUqwvXQPR7GTphVmEaEZWqIGK27hHIhAYMlFO3bbCeGSaIHANOJ+tkmVx2hTuDg3Y4U4eajngLu7XFE7Amg5TjxjP+Oe4JrAK7SfXSNDz2X+dPLj2XZ+V7/ut7UqX3LqXEbigSiBVjm7JmNYcGLovoNRDmoaqVR1689vZ3LLJ4ewHUO3CZWPdjEy8se3PwEeAujfCY+VWC5wBbxjg85uhRD77ClX/FtoPK5aj/k3HCAVTaYR3KSP/emj/ebu5kJT15MXV5dMqyuUzbxVLdVPP2A6edZzVETKvZqq+qHt2zNsII0Q=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
