site_name: clients
site_url: https://coady.github.io/clients/
site_description: High-level HTTP clients for Python.
theme: material

repo_name: coady/clients
repo_url: https://github.com/coady/clients
edit_uri: ""

nav:
  - Introduction: index.md
  - Reference: reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: true
